-- MySQL Script generated by MySQL Workbench
-- Wed Sep 28 15:01:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`players` (
  `id` INT NOT NULL,
  `nick` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `playerscol` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `x` INT NULL,
  `y` INT NULL,
  `players_id` INT NOT NULL,
  PRIMARY KEY (`id`, `players_id`),
  CONSTRAINT `fk_Villages_players`
    FOREIGN KEY (`players_id`)
    REFERENCES `mydb`.`players` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Buildings` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`resources` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`troops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`troops` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `damage` INT NULL,
  `distance_damage` INT NULL,
  `defense` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages_has_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages_has_resources` (
  `Villages_id` INT NOT NULL,
  `Villages_players_id` INT NOT NULL,
  `resources_id` INT NOT NULL,
  `value` INT NULL,
  PRIMARY KEY (`Villages_id`, `Villages_players_id`, `resources_id`),
  CONSTRAINT `fk_Villages_has_resources_Villages1`
    FOREIGN KEY (`Villages_id` , `Villages_players_id`)
    REFERENCES `mydb`.`Villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Villages_has_resources_resources1`
    FOREIGN KEY (`resources_id`)
    REFERENCES `mydb`.`resources` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages_has_Buildings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages_has_Buildings` (
  `Villages_id` INT NOT NULL,
  `Villages_players_id` INT NOT NULL,
  `Buildings_id` INT NOT NULL,
  PRIMARY KEY (`Villages_id`, `Villages_players_id`, `Buildings_id`),
  CONSTRAINT `fk_Villages_has_Buildings_Villages1`
    FOREIGN KEY (`Villages_id` , `Villages_players_id`)
    REFERENCES `mydb`.`Villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Villages_has_Buildings_Buildings1`
    FOREIGN KEY (`Buildings_id`)
    REFERENCES `mydb`.`Buildings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Villages_has_troops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Villages_has_troops` (
  `Villages_id` INT NOT NULL,
  `Villages_players_id` INT NOT NULL,
  `troops_id` INT NOT NULL,
  PRIMARY KEY (`Villages_id`, `Villages_players_id`, `troops_id`),
  CONSTRAINT `fk_Villages_has_troops_Villages1`
    FOREIGN KEY (`Villages_id` , `Villages_players_id`)
    REFERENCES `mydb`.`Villages` (`id` , `players_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Villages_has_troops_troops1`
    FOREIGN KEY (`troops_id`)
    REFERENCES `mydb`.`troops` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
